#!/usr/bin/env python
import sys
import json

args = (sys.argv)

trainingFileName = args[1]

trainingFile = open(trainingFileName, "r")

people = []

for line in trainingFile:
	voting = line.split(",")
	people.append(voting)
